language: ruby
script: bundle exec rake spec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
gemfile:
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x
